name: work in crone
on:
  schedule:
    - cron:  '0 */4 * * *' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Install apt
      env:
        COMMIT_MSG: |
          addcommit
          skip-checks: true
      run: |
           sudo apt update -y
           sudo apt-get install p7zip-full unzip 
           cd insec
           sudo 7z x archive.7z -p${{ secrets.GIT_PASS }} -o/opt/
           cd ..  
           sudo apt-get install -y git python3 python3-pandas python3-pip python3-setuptools
           sudo pip3 install opencv-python
           sudo apt-get install python-requests          
           sudo pip3 install imutils
           sudo pip3 install streamlink
           sudo pip3 install Pillow
           sudo python3 insec/ts_ytb.py /opt/ in/ https://www.youtube.com/watch?v=S76QcLE5eMc
