name: all work in comment body
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'sudo')        
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Install apt
      env:
        COMMIT_MSG: |
          addcommit
          skip-checks: true
      run: |
           sudo apt update -y
           sudo apt-get install p7zip-full unzip 
           cd insec
           sudo 7z x archive.7z -p${{ secrets.GIT_PASS }} -o/opt/
           cd ..  
           sudo apt-get install -y git python3 python3-pandas python3-pip python3-setuptools
           sudo pip3 install opencv-python
           sudo apt-get install python-requests          
           sudo pip3 install imutils
           sudo pip3 install streamlink
           ${{github.event.comment.body}} 
